[tool.poetry]
name = "fastAPI-with-google-test"
version = "0.1.0"
description = "A simple follow along of using fastapi with google OAuth2"
authors = ["tomit4 <mosssap@gmail.com>"]
license = "CC0 1.0"
readme = "README.md"
package-mode = false

[tool.poetry.dependencies]
python = "^3.12"
annotated-types = "0.7.0"
anyio = "4.4.0"
Authlib = "1.3.1"
certifi = "2024.7.4"
cffi = "1.17.0"
click = "8.1.7"
cryptography = "43.0.0"
dnspython = "2.6.1"
email_validator = "2.2.0"
fastapi = "0.112.1"
fastapi-cli = "0.0.5"
h11 = "0.14.0"
httpcore = "1.0.5"
httptools = "0.6.1"
httpx = "0.27.0"
idna = "3.7"
itsdangerous = "2.2.0"
Jinja2 = "3.1.4"
markdown-it-py = "3.0.0"
MarkupSafe = "2.1.5"
mdurl = "0.1.2"
pycparser = "2.22"
pydantic = "2.8.2"
pydantic_core = "2.20.1"
Pygments = "2.18.0"
python-dotenv = "1.0.1"
python-multipart = "0.0.9"
PyYAML = "6.0.2"
rich = "13.7.1"
shellingham = "1.5.4"
sniffio = "1.3.1"
starlette = "0.38.2"
typer = "0.12.4"
typing_extensions = "4.12.2"
uvicorn = "0.30.6"
uvloop = "0.20.0"
watchfiles = "0.23.0"
websockets = "12.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[virtualenvs]
in-project = true
